from app.models.role import Role
from app.models.department import Department
from app.models.production_line import ProductionLine
from app.models.machine import Machine
from app.models.issue_category import IssueCategory
from app.models.user import User
from app.models.incident import Incident
from app.models.ticket import Ticket
from app.models.downtime_record import DowntimeRecord
from app.models.rca_record import RCARecord
from app.models.capa_record import CAPARecord
from app.models.resolution_record import ResolutionRecord
from app.models.ml_prediction import MLPrediction
from app.models.notification import Notification
from app.models.incident_activity_log import IncidentActivityLog